FROM node:22-slim

WORKDIR /app

# Define build-time arguments
ARG SESSION_SECRET
ARG DATABASE_URL
ARG SMTP_HOST
ARG SMTP_PORT
ARG SMTP_USER
ARG SMTP_PASS
ARG SMTP_FROM
ARG NEXT_PUBLIC_APP_URL

# Set environment variables for build and runtime
ENV SESSION_SECRET=$SESSION_SECRET
ENV DATABASE_URL=$DATABASE_URL
ENV SMTP_HOST=$SMTP_HOST
ENV SMTP_PORT=$SMTP_PORT
ENV SMTP_USER=$SMTP_USER
ENV SMTP_PASS=$SMTP_PASS
ENV SMTP_FROM=$SMTP_FROM
ENV NEXT_PUBLIC_APP_URL=$NEXT_PUBLIC_APP_URL
ENV PORT=3001

COPY package*.json ./
RUN npm ci
COPY . .
RUN npx prisma generate
RUN npm run build

EXPOSE 3001
CMD ["npm", "run", "start"]